# Values for cert-manager dependency
cert-manager:
  crds:
    enabled: true

# Your custom values
clusterIssuer:
  email: bob@bomar.us  # Update this
  #server: https://acme-v02.api.letsencrypt.org/directory
  server: https://acme-staging-v02.api.letsencrypt.org/directory

wildcard:
  domain: "*.{{ .Values.clusterName }}.{{ .Values.domainname }}"
  dnsNames:
    - "{{ .Values.clusterName }}.{{ .Values.domainname }}"
    - "*.{clusterName}.{{ .Values.domainname }}"