persistence:
  config:
    enabled: true
  transcode:
    enabled: true
service:
  dnla-tcp:
    enabled: true
  dnla-udp:
    enabled: true
ingress:
  main:
    enabled: true
    hosts:
      - host: plex.pirate.abode.tailandtaillabs.org
        paths:
          - /
    tls:
      - secretName: wildcard-tls
        hosts:
          - plex.pirate.abode.tailandtaillabs.org
hostNetwork: true