apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-config
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.pvc.storageClass }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}