ingress:
  main:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: "placeholder"
        paths:
          - path: /radarr
            pathType: Prefix
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.middlewares: radarr-stripprefix@kubernetescrd
    tls:
      - secretName: wildcard-tls
        hosts:
          - "placeholder"

persistence:
  config:
    enabled: true
    storageClass: "local-path"
    size: 1Gi
  media:
    enabled: true
    type: nfs
    server: danas.hangar.bpfx.org
    path: /volume1/dataz
    mountPath: /media