apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr-routes
  namespace: radarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pirate.abode.tailandtraillabs.org`) && PathPrefix(`/radarr`)
      kind: Rule
      services:
        - name: pirate-radarr
          namespace: radarr
          port: 7878