ingress: 
  enabled: true
  hosts:
    - host: "{{ .Values.clusterName }}.{{ .Values.domainName }}"
      paths:
        - path: /
          pathType: Prefix
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: "wildcard-tls"
      hosts:
        - "{{ .Values.clusterName }}.{{ .Values.domainName }}"
config:
  baseURL: "https://{{ .Values.clusterName }}.{{ .Values.domainName }}"
env:
  - name: KUBERNETES_SERVICE_HOST
    value: "localhost"
  - name: KUBERNETES_SERVICE_PORT
    value: "6443"

