jellyfin:
  ingress:
    enabled: true
    hosts:
      - host: jellyfin.pirate.abode.tailandtraillabs.org
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: wildcard-tls
        hosts:
          - jellyfin.pirate.abode.tailandtraillabs.org
  persistence:
    storageClass: local-path
  media:
    enabled: true
    existingClaim: "media-nfs"