jellyfin:
  ingress:
    enabled: true
    hosts:
      - host: jellyfin.pirate.tailandtraillabs.org
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: wildcard-tls
        hosts:
          - jellyfin.pirate.tailandtraillabs.org
  persistence:
    storageClass: local-path
    media:
      enabled: true
      existingClaim: "pirate-jellyfin-media"
      accessMode: ReadWriteMany
      size: 1Ti
  volumes:
    - name: dri
      hostPath:
        path: /dev/dri