apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sabnzbd
  namespace: sabnzbd
  annotations:
    external-dns.alpha.kubernetes.io/hostname: sabnzbd.lab.tailandtraillabs.com
    external-dns.alpha.kubernetes.io/target: intrepid.hangar.bpfx.org
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`sabnzbd.lab.tailandtraillabs.com`)
      services:
        - name: sabnzbd
          port: 8080
  tls:
    secretName: wildcard-tls-prod
