apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kargo
  namespace: kargo
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kargo.lab.tailandtraillabs.com
    external-dns.alpha.kubernetes.io/target: intrepid.hangar.bpfx.org
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`kargo.lab.tailandtraillabs.com`)
      services:
        - name: kargo-api
          port: 443
  tls:
    secretName: wildcard-tls-prod
