apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr
  namespace: prowlarr
  annotations:
    external-dns.alpha.kubernetes.io/hostname: prowlarr.lab.tailandtraillabs.com
    external-dns.alpha.kubernetes.io/target: intrepid.hangar.bpfx.org
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`prowlarr.lab.tailandtraillabs.com`)
      services:
        - name: prowlarr
          port: 9696
  tls:
    secretName: wildcard-tls-prod
