---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: otel-collector-grpc
  namespace: opentelemetry-operator
spec:
  entryPoints:
    - otel-grpc
  routes:
    - match: HostSNI(`*`)
      services:
        - name: otel-collector
          port: 4317
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: otel-collector-http
  namespace: opentelemetry-operator
spec:
  entryPoints:
    - otel-http
  routes:
    - match: HostSNI(`*`)
      services:
        - name: otel-collector
          port: 4318
