apiVersion: v2
name: kube-prometheus-stack
description: kube-prometheus-stack
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: kube-prometheus-stack
    version: 80.4.1
    repository: "https://prometheus-community.github.io/helm-charts"